### ISSUE TITLE
Is there any way to see quickstart plugins works ok?

### ISSUE THREAD

**Issue by kdszh** [naver/pinpoint-c-agent#29] opened 2018-09-18 06:54 UTC
Hi,

Is there any way to see the quickstart plugins loads and works ok?  I set the pluginEntryFile and  PluginRootDir a wrong path as below, and restart pinpoint agent ,but I can not find any [ERROR] in pinpoint_log.txt.

pinpoint_agent.conf:
[PHP]
PluginEntryFile=plugins_create2.php
PluginRootDir=/data/www/pinpoint/quickstart/php/web/plugins2

 pinpoint_log.txt:
 2018-09-18 14:42:18 [pinpoint] [8851] pinpoint_api.cpp:173 [INFO] PHP.PluginEntryFile=plugins_create1.php
 2018-09-18 14:42:18 [pinpoint] [8851] pinpoint_api.cpp:173 [INFO] PHP.PluginRootDir=/data/www/pinpoint/quickstart/php/web/plugins2

Help.
[pinpoint_agent.conf.txt](https://github.com/naver/pinpoint-c-agent/files/2391498/pinpoint_agent.conf.txt)
[pinpoint_log.txt](https://github.com/naver/pinpoint-c-agent/files/2391499/pinpoint_log.txt)

**Comment by kdszh** [comment] 2018-09-18 09:43
I put some debug code in quickstart_plugin.php，restart php ，but still no debug output message：
pinpoint_log(PINPOINT_DEBUG, "quickstart plugin works");

**Comment by eeliu** [comment] 2018-09-19 02:14
@kdszh  
Could U give me all file in PluginRootDir(/data/www/pinpoint/quickstart/php/web/plugins2 include plugins_create2.php), I can't reproduce this in my env.

**Comment by kdszh** [comment] 2018-09-19 06:30
sorry, there is no file in  /data/www/pinpoint/quickstart/php/web/plugins2, I just want to know how can I ensure that my plugin is successfully loaded ( because I think the quickstart plugin does not work) @eeliu

**Comment by eeliu** [comment] 2018-09-19 06:50
@kdszh
yes, if you did that, agent do nothing.

This is the way to load plugins (written by php), so if "/data/www/pinpoint/quickstart/php/web/plugins2/plugins_create2.php" did not exsit, agent do nothing. 

By the way, there are some plugin examples in "pinpoint-c-agent/simulate/web/php/plugins/".
Hope this could help u.

**Comment by kdszh** [comment] 2018-09-19 07:29
ok.   Is there any way to know the plugins works ( like print some debug message to log file...)?
here is the example in my env, i guess the CurlPlugin does not work.
![aa](https://user-images.githubusercontent.com/2100801/45737551-bb2c0600-bc20-11e8-857a-e69473615060.png)
![bb](https://user-images.githubusercontent.com/2100801/45737557-bff0ba00-bc20-11e8-8fb2-2f29a7d40d23.png)

**Comment by eeliu** [comment] 2018-09-19 09:34
@kdszh  

There are 2 way to debug your plugins
1. Use pinpoint_log 

``` php
    pinpoint_log(PINPOINT_DEBUG, "quickstart plugin works");
```
2. The plugin file is a php script file, you can print message as you debug the common php file.

``` php
  echo "hello, today";
  print_r(array);

```

> CurlPlugin  does not work

hmm, I need more information ( pinpoint_agent.conf ,pinpoint_log.txt, and your plugins files )

**Comment by kdszh** [comment] 2018-09-20 03:00
thanks ,i will post the result later @eeliu

**Comment by ChenGXQQ** [comment] 2018-09-20 07:32
@kdszh Do you visit any page? The agent will start after you visit the first page. Please do this and update the log file. We can check more.

**Comment by eeliu** [comment] 2018-09-20 07:58
@kdszh  
From you [pinpoint_log.txt](https://github.com/naver/pinpoint-c-agent/files/2400133/pinpoint_log.txt), no php plugins had added.

Pls check the below

1. Did your web site running success ?
2. Access http://xxx:xxx/path to plugins_create.php, did it ok (no error message) ?

if failed, post the error message to us.

> Note
plugins_create.php only called once when php-fpm (libphp5.so) get the first request.

**Comment by kdszh** [comment] 2018-09-20 10:49
after access my web site , I can see the debug message now. 
is there any example for PhpInternalFunctionsPlugin ?  I want to get some result like this:
![default](https://user-images.githubusercontent.com/2100801/45813675-cefd6800-bd05-11e8-9900-12beff7c964a.png)

**Comment by eeliu** [comment] 2018-09-21 09:03
https://github.com/naver/pinpoint-c-agent/blob/dev/simulate/web/php/plugins/quickstart_plugin.php 

goto the "GetDateInterceptor".

@kdszh

**Comment by kdszh** [comment] 2018-09-23 09:32
@eeliu thanks very much.

**Comment by sky-sunny** [comment] 2019-05-22 05:22
> 转到“GetDateInterceptor”
> https://github.com/naver/pinpoint-c-agent/blob/7c1c62459551f80d7076dfe3017586b346afd4e7/simulate/web/php/plugins/quickstart_plugin.php#L18
> 
> 或使用
> 
> https://github.com/naver/pinpoint-c-agent/blob/7c1c62459551f80d7076dfe3017586b346afd4e7/simulate/web/php/plugins/quickstart_plugin.php#L561
> 
> @kdszh


# PhpInternalFunctionsPlugin
PluginExclude = PhpInternalFunctionsPlugin  ####Modify this option to ____________?
luginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;    Modify this option to ____________?


[PHP]
PluginEntryFile=plugins_create.php  ####Modify this file?
PluginRootDir=/usr/local/php/etc/web/plugins

**Comment by eeliu** [comment] 2019-08-16 09:38
Hi @kdszh 
In PHP project, the easiest way to see how it works it use PHP to debug it.

https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.0 had fully supported plugins wroten by PHP. Hope you use it.
So I close this issue, if you find new problems, create a new one.

**Closed by eeliu** 2019-08-16 09:38 UTC
